#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_ENV="$ROOT_DIR/.env"
OUTPUT_ENV="$ROOT_DIR/server/.env"
MODE="production"

usage() {
  cat <<'EOF'
Usage:
  bash scripts/render-server-env.sh [options]

Options:
  --source <path>    Source env file (default: ./.env)
  --output <path>    Output env file (default: ./server/.env)
  --mode <mode>      Render mode: production|development (default: production)
  --help             Show this help text.
EOF
}

resolve_path() {
  local input="$1"
  if [[ "$input" = /* ]]; then
    printf "%s" "$input"
  else
    printf "%s/%s" "$ROOT_DIR" "$input"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source)
      SOURCE_ENV="$(resolve_path "${2:-}")"
      shift 2
      ;;
    --output)
      OUTPUT_ENV="$(resolve_path "${2:-}")"
      shift 2
      ;;
    --mode)
      MODE="${2:-}"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ "$MODE" != "production" && "$MODE" != "development" ]]; then
  echo "Unsupported --mode value: $MODE" >&2
  exit 1
fi

if [[ ! -f "$SOURCE_ENV" ]]; then
  echo "Source env file not found: $SOURCE_ENV" >&2
  exit 1
fi

read_env_value() {
  local key="$1"
  local value
  value="$(grep -E "^${key}=" "$SOURCE_ENV" | tail -n1 | cut -d= -f2- || true)"
  printf "%s" "$value"
}

is_placeholder() {
  local value
  value="$(printf "%s" "$1" | tr '[:upper:]' '[:lower:]')"
  if [[ -z "$value" ]]; then
    return 0
  fi
  if [[ "$value" == *"replace-with"* || "$value" == *"your-"* || "$value" == *"example"* ]]; then
    return 0
  fi
  return 1
}

KEY_ENCRYPTION_SECRET="$(read_env_value KEY_ENCRYPTION_SECRET)"
if is_placeholder "$KEY_ENCRYPTION_SECRET" || [[ ${#KEY_ENCRYPTION_SECRET} -lt 16 ]]; then
  echo "KEY_ENCRYPTION_SECRET must be set in $SOURCE_ENV with at least 16 non-placeholder chars." >&2
  exit 1
fi

CLERK_SECRET_KEY="$(read_env_value CLERK_SECRET_KEY)"
ALLOW_INSECURE_DEV_AUTH="$(read_env_value ALLOW_INSECURE_DEV_AUTH)"
if [[ "$MODE" == "production" ]]; then
  ALLOW_INSECURE_DEV_AUTH="false"
  if [[ -z "$CLERK_SECRET_KEY" ]]; then
    echo "CLERK_SECRET_KEY must be set in $SOURCE_ENV for production mode." >&2
    exit 1
  fi
fi
if [[ -z "$ALLOW_INSECURE_DEV_AUTH" ]]; then
  ALLOW_INSECURE_DEV_AUTH="true"
fi

STREAM_TICKET_SECRET="$(read_env_value STREAM_TICKET_SECRET)"
if is_placeholder "$STREAM_TICKET_SECRET" || [[ ${#STREAM_TICKET_SECRET} -lt 16 ]]; then
  STREAM_TICKET_SECRET="$KEY_ENCRYPTION_SECRET"
fi

REQUIRE_REDIS_FOR_READY="$(read_env_value REQUIRE_REDIS_FOR_READY)"
if [[ -z "$REQUIRE_REDIS_FOR_READY" ]]; then
  if [[ "$MODE" == "production" ]]; then
    REQUIRE_REDIS_FOR_READY="true"
  else
    REQUIRE_REDIS_FOR_READY="false"
  fi
fi

NODE_ENV_VALUE="$MODE"
if [[ "$MODE" == "development" ]]; then
  NODE_ENV_VALUE="development"
fi

STREAM_TICKET_TTL_SECONDS="$(read_env_value STREAM_TICKET_TTL_SECONDS)"
MAINTENANCE_INTERVAL_MS="$(read_env_value MAINTENANCE_INTERVAL_MS)"
TOMBSTONE_RETENTION_MS="$(read_env_value TOMBSTONE_RETENTION_MS)"
NOTE_CHANGES_RETENTION_MS="$(read_env_value NOTE_CHANGES_RETENTION_MS)"
SYNC_BATCH_LIMIT="$(read_env_value SYNC_BATCH_LIMIT)"
SYNC_PULL_LIMIT="$(read_env_value SYNC_PULL_LIMIT)"
LOG_LEVEL="$(read_env_value LOG_LEVEL)"
AUTH_DEV_USER_ID="$(read_env_value AUTH_DEV_USER_ID)"
CLERK_PUBLISHABLE_KEY="$(read_env_value CLERK_PUBLISHABLE_KEY)"

mkdir -p "$(dirname "$OUTPUT_ENV")"
umask 077

{
  echo "# Generated by scripts/render-server-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "NODE_ENV=$NODE_ENV_VALUE"
  echo "ALLOW_INSECURE_DEV_AUTH=$ALLOW_INSECURE_DEV_AUTH"
  echo "KEY_ENCRYPTION_SECRET=$KEY_ENCRYPTION_SECRET"
  echo "STREAM_TICKET_SECRET=$STREAM_TICKET_SECRET"
  echo "CLERK_SECRET_KEY=$CLERK_SECRET_KEY"
  echo "CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY"
  echo "REQUIRE_REDIS_FOR_READY=$REQUIRE_REDIS_FOR_READY"
  [[ -n "$STREAM_TICKET_TTL_SECONDS" ]] && echo "STREAM_TICKET_TTL_SECONDS=$STREAM_TICKET_TTL_SECONDS"
  [[ -n "$MAINTENANCE_INTERVAL_MS" ]] && echo "MAINTENANCE_INTERVAL_MS=$MAINTENANCE_INTERVAL_MS"
  [[ -n "$TOMBSTONE_RETENTION_MS" ]] && echo "TOMBSTONE_RETENTION_MS=$TOMBSTONE_RETENTION_MS"
  [[ -n "$NOTE_CHANGES_RETENTION_MS" ]] && echo "NOTE_CHANGES_RETENTION_MS=$NOTE_CHANGES_RETENTION_MS"
  [[ -n "$SYNC_BATCH_LIMIT" ]] && echo "SYNC_BATCH_LIMIT=$SYNC_BATCH_LIMIT"
  [[ -n "$SYNC_PULL_LIMIT" ]] && echo "SYNC_PULL_LIMIT=$SYNC_PULL_LIMIT"
  [[ -n "$LOG_LEVEL" ]] && echo "LOG_LEVEL=$LOG_LEVEL"
  [[ -n "$AUTH_DEV_USER_ID" ]] && echo "AUTH_DEV_USER_ID=$AUTH_DEV_USER_ID"
} > "$OUTPUT_ENV"

chmod 600 "$OUTPUT_ENV"
echo "Rendered $OUTPUT_ENV from $SOURCE_ENV ($MODE mode)."
